variables:
  GIT_SUBMODULE_STRATEGY: recursive

build-lx-clang:
  image: lucasvellactw/glome-ci
  stage: build
  script:
  - export
  - mkdir build-clang
  - cd build-clang
  - cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../toolchain/clang.cmake -DENABLE_IPO=On -DEXTRA_CXX_FLAGS="-Ofast -march=haswell -mtune=generic"
  - cmake --build ./
  artifacts:
    paths:
    - $CI_PROJECT_DIR/build-clang/src/sdl/glome
  # only:
  # - master

build-lx-g++:
  image: lucasvellactw/glome-ci
  stage: build
  script:
  - export
  - mkdir build-gcc
  - cd build-gcc
  - cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DENABLE_IPO=On -DEXTRA_CXX_FLAGS="-Ofast -march=haswell -mtune=generic"
  - cmake --build ./
  artifacts:
    paths:
    - $CI_PROJECT_DIR/build-gcc/src/sdl/glome
  # only:
  # - master

build-mswin64-g++:
  image: lucasvellactw/glome-ci
  stage: build
  script:
  - export
  - mkdir build-mswin64
  - cd build-mswin64
  - /opt/windows-deps/windows-build-cross.sh ..
  - cmake --build ./
  artifacts:
    paths:
    - $CI_PROJECT_DIR/build-mswin64/src/sdl/glome.exe
  # only:
  # - master
