variables:
  GIT_SUBMODULE_STRATEGY: recursive

build-lx-clang:
  image: lucasvellactw/glome-ci
  stage: build
  script:
  - export
  - mkdir build-clang
  - cd build-clang
  - cmake .. -G Ninja -DCMAKE_TOOLCHAIN_FILE=../toolchain/clang.cmake
  - cmake --build ./
  artifacts:
    paths:
    - $CI_PROJECT_DIR/build/src/sdl/glome
  # only:
  # - master

build-lx-g++:
  image: lucasvellactw/glome-ci
  stage: build
  script:
  - export
  - mkdir build-gcc
  - cd build-gcc
  - cmake .. -G Ninja
  - cmake --build ./
  artifacts:
    paths:
    - $CI_PROJECT_DIR/build/src/sdl/glome
  # only:
  # - master

# build-win:
  # image: ???
# ...
